/**
 * <copyright>
 * </copyright>
 *
 * $Id: ExtensionAspectValidator.java,v 1.1 2008/03/17 14:39:13 jkohnlein Exp $
 */
package org.eclipse.xpand3.declaration.validation;

import org.eclipse.xpand3.expression.AbstractExpression;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.declaration.ExtensionAspect}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExtensionAspectValidator {
	boolean validate();

	boolean validateExpression(AbstractExpression value);
}
