/**
 * <copyright>
 * </copyright>
 *
 * $Id: JavaExtensionValidator.java,v 1.1 2008/03/17 14:39:13 jkohnlein Exp $
 */
package org.eclipse.xpand3.declaration.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xpand3.Identifier;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.declaration.JavaExtension}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JavaExtensionValidator {
	boolean validate();

	boolean validateJavaType(Identifier value);
	boolean validateJavaMethod(Identifier value);
	boolean validateJavaParamTypes(EList<Identifier> value);
}
