<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="incrementaltest"
    nsURI="http://www.eclipse.org/m2t/xpand/incrementaltest.ecore" nsPrefix="incrementaltest">
  <eClassifiers xsi:type="ecore:EClass" name="FirstClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeOne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceToSecondClass"
        eType="#//SecondClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecondClass" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeTwo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FourthClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeFour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnchangedClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassWithNewAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="added" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassWithRemovedAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassWithNewSuperType" eSuperTypes="#//UnchangedClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassWithRemovedSuperType"/>
</ecore:EPackage>
