/**
 * <copyright>
 * </copyright>
 *
 * $Id: CallableValidator.java,v 1.1 2009/09/08 09:39:40 hbehrens Exp $
 */
package org.eclipse.xtend.profiler.profilermodel.validation;


/**
 * A sample validator interface for {@link org.eclipse.xtend.profiler.profilermodel.Callable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CallableValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateTime(long value);
	boolean validateChildTime(long value);
	boolean validateSelfTime(long value);
	boolean validateOutboundChildTime(long value);
}
