/**
 * <copyright>
 * </copyright>
 *
 * $Id: CallGroupValidator.java,v 1.1 2009/09/08 09:39:40 hbehrens Exp $
 */
package org.eclipse.xtend.profiler.profilermodel.validation;

import org.eclipse.xtend.profiler.profilermodel.Item;

/**
 * A sample validator interface for {@link org.eclipse.xtend.profiler.profilermodel.CallGroup}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CallGroupValidator {
	boolean validate();

	boolean validateInvoker(Item value);
	boolean validateSubroutine(Item value);
	boolean validateCount(int value);
	boolean validateTime(long value);
}
