/**
 * <copyright>
 * </copyright>
 *
 * $Id: MyMetaClassValidator.java,v 1.1 2008/10/21 07:32:51 jkohnlein Exp $
 */
package org.eclipse.xtend.typesystem.emf.check.model.test.validation;


import org.eclipse.emf.common.util.EList;
import org.eclipse.xtend.typesystem.emf.check.model.test.MyMetaClass;

/**
 * A sample validator interface for {@link org.eclipse.xtend.typesystem.emf.check.model.test.MyMetaClass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MyMetaClassValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateChildren(EList<MyMetaClass> value);
}
