/**
 * <copyright>
 * </copyright>
 *
 * $Id: LiteralValidator.java,v 1.1 2008/03/06 15:35:10 jkohnlein Exp $
 */
package org.eclipse.xpand3.expression.validation;

import org.eclipse.xpand3.Identifier;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.expression.Literal}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LiteralValidator {
	boolean validate();

	boolean validateLiteralValue(Identifier value);
}
