/**
 * <copyright>
 * </copyright>
 *
 * $Id: NullLiteralValidator.java,v 1.1 2008/03/17 14:39:11 jkohnlein Exp $
 */
package org.eclipse.xpand3.expression.validation;


/**
 * A sample validator interface for {@link org.eclipse.xpand3.expression.NullLiteral}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NullLiteralValidator {
	boolean validate();

}
