/**
 * <copyright>
 * </copyright>
 *
 * $Id: AbstractAspectValidator.java,v 1.1 2008/03/06 15:35:13 jkohnlein Exp $
 */
package org.eclipse.xpand3.declaration.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xpand3.DeclaredParameter;
import org.eclipse.xpand3.Identifier;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.declaration.AbstractAspect}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractAspectValidator {
	boolean validate();

	boolean validatePointcut(Identifier value);
	boolean validateParams(EList<DeclaredParameter> value);
	boolean validateWildparams(boolean value);
}
