/**
 * <copyright>
 * </copyright>
 *
 * $Id: ExpandStatementValidator.java,v 1.1 2008/03/17 14:39:10 jkohnlein Exp $
 */
package org.eclipse.xpand3.statement.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xpand3.Identifier;

import org.eclipse.xpand3.expression.AbstractExpression;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.statement.ExpandStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpandStatementValidator {
	boolean validate();

	boolean validateForeach(boolean value);
	boolean validateParameters(EList<AbstractExpression> value);
	boolean validateSeparator(AbstractExpression value);
	boolean validateTarget(AbstractExpression value);
	boolean validateDefinition(Identifier value);
}
