package org.eclipse.xtend.typesystem.emf.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

/*
 * automatically generated by org.eclipse.emf.mwe.releng.GenerateTestSuite 
 * 
 * @generated 
 */
public class AllTests {
   public static Test suite() {
      TestSuite suite = new TestSuite("Tests for org.eclipse.xtend.typesystem.emf.tests");
      suite.addTestSuite(org.eclipse.xtend.typesystem.emf.EmfMetaModelTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.emf.EnumTypeTest.class);
      return suite;
   }
}
