<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="staticTypesystem"
    nsURI="http://www.eclipse.org/m2t/xpand3/staticTypesystem" nsPrefix="staticTypesystem">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTypeReference" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//AbstractTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredType" lowerBound="1"
        eType="#//DeclaredType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualTypeArguments" upperBound="-1"
        eType="#//AbstractTypeReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeVariable" eSuperTypes="#//AbstractTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredTypeParameter"
        lowerBound="1" eType="#//DeclaredTypeParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoidType" eSuperTypes="#//AbstractTypeReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="WildcardType" eSuperTypes="#//AbstractTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBounds" upperBound="-1"
        eType="#//AbstractTypeReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBounds" upperBound="-1"
        eType="#//AbstractTypeReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionType" eSuperTypes="#//AbstractTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredFunction" lowerBound="1"
        eType="#//DeclaredFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualTypeArguments" upperBound="-1"
        eType="#//AbstractTypeReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaredType" eSuperTypes="#//AbstractNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticProperties" upperBound="-1"
        eType="#//DeclaredStaticProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//DeclaredProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredTypeParameters"
        upperBound="-1" eType="#//DeclaredTypeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1"
        eType="#//AbstractTypeReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaredFunction" eSuperTypes="#//AbstractNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParameters" upperBound="-1"
        eType="#//DeclaredParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredTypeParameters"
        upperBound="-1" eType="#//DeclaredTypeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//AbstractTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaredProperty" eSuperTypes="#//AbstractNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//AbstractTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaredStaticProperty" eSuperTypes="#//AbstractNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaredTypeParameter" eSuperTypes="#//AbstractNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBounds" upperBound="-1"
        eType="#//AbstractTypeReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaredParameter" eSuperTypes="#//AbstractNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//AbstractTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//DeclaredType" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
