<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="staticTypesystem"
    nsURI="http://www.eclipse.org/m2t/xpand3/staticTypesystem" nsPrefix="staticTypesystem">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTypeReference" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//AbstractTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredType" lowerBound="1"
        eType="#//declaration/DeclaredType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualTypeArguments" upperBound="-1"
        eType="#//AbstractTypeReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeVariable" eSuperTypes="#//AbstractTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredTypeParameter"
        lowerBound="1" eType="#//declaration/DeclaredTypeParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoidType" eSuperTypes="#//AbstractTypeReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="WildcardType" eSuperTypes="#//AbstractTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBounds" upperBound="-1"
        eType="#//AbstractTypeReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBounds" upperBound="-1"
        eType="#//AbstractTypeReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionType" eSuperTypes="#//AbstractTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredFunction" lowerBound="1"
        eType="#//declaration/DeclaredFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualTypeArguments" upperBound="-1"
        eType="#//AbstractTypeReference"/>
  </eClassifiers>
  <eSubpackages name="declaration" nsURI="http://www.eclipse.org/m2t/xpand3/staticTypesystem/declaration"
      nsPrefix="declaration">
    <eClassifiers xsi:type="ecore:EClass" name="DeclaredType" eSuperTypes="#//AbstractNamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="staticProperties" upperBound="-1"
          eType="#//declaration/DeclaredStaticProperty" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//declaration/DeclaredProperty" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          eType="#//declaration/DeclaredOperation" containment="true" eOpposite="#//declaration/DeclaredOperation/declaringType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredTypeParameters"
          upperBound="-1" eType="#//declaration/DeclaredTypeParameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeclaredOperation" eSuperTypes="#//AbstractNamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParameters" upperBound="-1"
          eType="#//declaration/DeclaredParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaringType" lowerBound="1"
          eType="#//declaration/DeclaredType" eOpposite="#//declaration/DeclaredType/operations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//declaration/DeclaredType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeclaredFunction" eSuperTypes="#//AbstractNamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParameters" upperBound="-1"
          eType="#//declaration/DeclaredParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredTypeParameters"
          upperBound="-1" eType="#//declaration/DeclaredTypeParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//declaration/DeclaredType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeclaredProperty" eSuperTypes="#//AbstractNamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeclaredStaticProperty" eSuperTypes="#//AbstractNamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeclaredTypeParameter" eSuperTypes="#//AbstractNamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeclaredParameter" eSuperTypes="#//AbstractNamedElement"/>
  </eSubpackages>
</ecore:EPackage>
