package org.eclipse.xpand.incremental.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

/*
 * automatically generated by org.eclipse.emf.mwe.releng.GenerateTestSuite 
 * 
 * @generated 
 */
public class AllTests {
   public static Test suite() {
      TestSuite suite = new TestSuite("Tests for org.eclipse.xpand.incremental.tests");
      suite.addTestSuite(org.eclipse.xpand.incremental.IncrementalCallbackTest.class);
      suite.addTestSuite(org.eclipse.xpand.incremental.IncrementalFacadeTest.class);
      suite.addTestSuite(org.eclipse.xpand.incremental.TraceTest.class);
      suite.addTestSuite(org.eclipse.xpand.incremental.CompareTest.class);
      return suite;
   }
}
