package org.eclipse.xtend.shared.ui.test;

import junit.framework.Test;
import junit.framework.TestSuite;

/*
 * automatically generated by org.eclipse.xpand.releng.GenerateTestSuites 
 * 
 * @generated 
 */
public class AllTests {
   public static Test suite() {
      TestSuite suite = new TestSuite("Tests for org.eclipse.xtend.shared.ui.test");
      suite.addTestSuite(org.eclipse.xtend.shared.ui.test.core.BuilderTest.class);
      suite.addTestSuite(org.eclipse.xtend.shared.ui.test.core.JdtJavaBeanTest.class);
      suite.addTestSuite(org.eclipse.xtend.shared.ui.test.core.JdtOawClassicTest.class);
      suite.addTestSuite(org.eclipse.xtend.shared.ui.test.core.metamodel.jdt.JdtMetaModelTest.class);
      suite.addTestSuite(org.eclipse.xtend.shared.ui.test.xpand2.core.ASTTest.class);
      suite.addTestSuite(org.eclipse.xtend.shared.ui.test.xpand2.core.JdtJavaBeanTest.class);
      suite.addTestSuite(org.eclipse.xtend.shared.ui.test.xpand2.core.SimpleProjectTest.class);
      suite.addTestSuite(org.eclipse.xtend.shared.ui.test.xpand2.core.XtendXpandProjectTest.class);
      suite.addTestSuite(org.eclipse.xtend.shared.ui.test.xpand2.emf.EmfXpandTest.class);
      suite.addTestSuite(org.eclipse.xtend.shared.ui.test.xpand2.core.ReferencedProjectTest.class);
      return suite;
   }
}
