/**
 * <copyright>
 * </copyright>
 *
 * $Id: FileStatementValidator.java,v 1.4 2008/03/12 09:54:30 jkohnlein Exp $
 */
package org.eclipse.xpand3.statement.validation;

import org.eclipse.xpand3.Identifier;

import org.eclipse.xpand3.expression.AbstractExpression;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.statement.FileStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FileStatementValidator {
	boolean validate();

	boolean validateFileNameExpression(AbstractExpression value);
	boolean validateOutletNameIdentifier(Identifier value);

	boolean validateOnce(boolean value);
}
