/**
 * <copyright>
 * </copyright>
 *
 * $Id: ForEachStatementValidator.java,v 1.5 2008/03/13 11:41:50 sefftinge Exp $
 */
package org.eclipse.xpand3.statement.validation;

import org.eclipse.xpand3.Identifier;

import org.eclipse.xpand3.expression.AbstractExpression;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.statement.ForEachStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ForEachStatementValidator {
	boolean validate();

	boolean validateTarget(AbstractExpression value);
	boolean validateSeperator(AbstractExpression value);
	boolean validateVariable(Identifier value);
	boolean validateIteratorName(Identifier value);
}
