/**
 * <copyright>
 * </copyright>
 *
 * $Id: IfStatementValidator.java,v 1.3 2008/03/07 11:10:48 jkohnlein Exp $
 */
package org.eclipse.xpand3.statement.validation;

import org.eclipse.xpand3.expression.AbstractExpression;

import org.eclipse.xpand3.statement.IfStatement;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.statement.IfStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IfStatementValidator {
	boolean validate();

	boolean validateCondition(AbstractExpression value);
	boolean validateUpperIf(IfStatement value);
	boolean validateElseIf(IfStatement value);
}
