/**
 * <copyright>
 * </copyright>
 *
 * $Id: TextStatementValidator.java,v 1.3 2008/03/07 11:10:48 jkohnlein Exp $
 */
package org.eclipse.xpand3.statement.validation;


/**
 * A sample validator interface for {@link org.eclipse.xpand3.statement.TextStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TextStatementValidator {
	boolean validate();

	boolean validateValue(String value);
	boolean validateDeleteLine(boolean value);
}
