/**
 * <copyright>
 * </copyright>
 *
 * $Id: CastedExpressionNodeValidator.java,v 1.3 2008/03/13 08:40:00 jkohnlein Exp $
 */
package org.eclipse.xpand3.internal.parser.xpand3node.validation;

import org.eclipse.tmf.common.node.CompositeNode;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.internal.parser.xpand3node.CastedExpressionNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CastedExpressionNodeValidator {
	boolean validate();

	boolean validateTarget(CompositeNode value);
	boolean validateType(CompositeNode value);
}
