/**
 * <copyright>
 * </copyright>
 *
 * $Id: IfExpressionNodeValidator.java,v 1.3 2008/03/13 08:39:59 jkohnlein Exp $
 */
package org.eclipse.xpand3.internal.parser.xpand3node.validation;

import org.eclipse.tmf.common.node.CompositeNode;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.internal.parser.xpand3node.IfExpressionNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IfExpressionNodeValidator {
	boolean validate();

	boolean validateThen(CompositeNode value);
	boolean validateElse(CompositeNode value);
	boolean validateCondition0(CompositeNode value);
	boolean validateCondition1(CompositeNode value);
}
