/**
 * <copyright>
 * </copyright>
 *
 * $Id: IfStatementNodeValidator.java,v 1.3 2008/03/12 09:54:13 jkohnlein Exp $
 */
package org.eclipse.xpand3.internal.parser.xpand3node.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.tmf.common.node.CompositeNode;


/**
 * A sample validator interface for {@link org.eclipse.xpand3.internal.parser.xpand3node.IfStatementNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IfStatementNodeValidator {
	boolean validate();

	boolean validateElseIf(EList<CompositeNode> value);

	boolean validateElse(CompositeNode value);

	boolean validateExpression(CompositeNode value);

	boolean validateElseIf(CompositeNode value);

	boolean validateSequence(CompositeNode value);

}
