/**
 * <copyright>
 * </copyright>
 *
 * $Id: InfixExpressionNodeValidator.java,v 1.2 2008/03/06 15:25:08 jkohnlein Exp $
 */
package org.eclipse.xpand3.internal.parser.xpand3node.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.tmf.common.node.CompositeNode;


/**
 * A sample validator interface for {@link org.eclipse.xpand3.internal.parser.xpand3node.InfixExpressionNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InfixExpressionNodeValidator {
	boolean validate();

	boolean validateCalls(EList<CompositeNode> value);

	boolean validateTarget(CompositeNode value);

	boolean validateCall(CompositeNode value);

	boolean validatePrimary(CompositeNode value);

}
