/**
 * <copyright>
 * </copyright>
 *
 * $Id: LetExpressionNodeValidator.java,v 1.2 2008/03/07 09:39:40 jkohnlein Exp $
 */
package org.eclipse.xpand3.internal.parser.xpand3node.validation;


/**
 * A sample validator interface for {@link org.eclipse.xpand3.internal.parser.xpand3node.LetExpressionNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LetExpressionNodeValidator {
	boolean validate();

}
