/**
 * <copyright>
 * </copyright>
 *
 * $Id: XNodeValidator.java,v 1.1 2008/03/07 11:11:14 jkohnlein Exp $
 */
package org.eclipse.xpand3.internal.parser.xpand3node.validation;

import org.eclipse.tmf.common.node.LeafNode;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.internal.parser.xpand3node.XNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XNodeValidator {
	boolean validate();

	boolean validateL(LeafNode value);
}
