/**
 * <copyright>
 * </copyright>
 *
 * $Id: FileValidator.java,v 1.3 2008/03/07 11:10:50 jkohnlein Exp $
 */
package org.eclipse.xpand3.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xpand3.ImportStatement;

import org.eclipse.xpand3.declaration.AbstractDeclaration;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.File}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FileValidator {
	boolean validate();

	boolean validateImports(EList<ImportStatement> value);
	boolean validateDeclarations(EList<AbstractDeclaration> value);
}
