/**
 * <copyright>
 * </copyright>
 *
 * $Id: ImportStatementValidator.java,v 1.3 2008/03/07 11:10:50 jkohnlein Exp $
 */
package org.eclipse.xpand3.validation;

import org.eclipse.xpand3.Identifier;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.ImportStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImportStatementValidator {
	boolean validate();

	boolean validateImportedId(Identifier value);
	boolean validateExported(boolean value);
}
