package org.eclipse.xpand.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

/*
 * automatically generated by org.eclipse.emf.mwe.releng.GenerateTestSuite 
 * 
 * @generated 
 */
public class AllTests {
   public static Test suite() {
      TestSuite suite = new TestSuite("Tests for org.eclipse.xpand.tests");
      suite.addTestSuite(org.eclipse.xpand.internal.tests.analyze.StatementAnalyzationTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.ast.ImportDeclarationTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.codeassist.FastAnalyzerTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.codeassist.KeywordProposalComputerTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.codeassist.StatementProposalComputerTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.evaluate.AopFeatureTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.evaluate.ProtectedRegionsTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.evaluate.StatementEvaluatorTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.GeneratorAdviceTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.GeneratorTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.impl.NameUtilTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.output.NoChangesVetoStrategyTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.output.OutputImplTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.parser.StatementParserTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.parser.XpandLexerTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.pr.ProtectedRegionResolverImplTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.pr.util.GenericFileFilterTest.class);
      suite.addTestSuite(org.eclipse.xpand.internal.tests.XpandUtilTest.class);
      return suite;
   }
}
