/**
 * <copyright>
 * </copyright>
 *
 * $Id: TypeVariableValidator.java,v 1.1 2008/03/17 14:39:19 jkohnlein Exp $
 */
package org.eclipse.xpand3.staticTypesystem.validation;

import org.eclipse.xpand3.staticTypesystem.DeclaredTypeParameter;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.staticTypesystem.TypeVariable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TypeVariableValidator {
	boolean validate();

	boolean validateDeclaredTypeParameter(DeclaredTypeParameter value);
}
