<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test"
    nsURI="http://www.itemis.de/emf.oaw.check.test" nsPrefix="test">
  <eClassifiers xsi:type="ecore:EClass" name="MyMetaClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//MyMetaClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subPackageRef" eType="#//subpackage/SubpackageMetaClass"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumAttr" eType="#//MyEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MyEnum">
    <eLiterals name="X"/>
    <eLiterals name="Y" value="1"/>
  </eClassifiers>
  <eSubpackages name="subpackage" nsURI="http://oaw.org/test/subpackage" nsPrefix="subpackage">
    <eClassifiers xsi:type="ecore:EClass" name="SubpackageMetaClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
