package org.eclipse.xtend.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

/*
 * automatically generated by org.eclipse.emf.mwe.releng.GenerateTestSuite 
 * 
 * @generated 
 */
public class AllTests {
   public static Test suite() {
      TestSuite suite = new TestSuite("Tests for org.eclipse.xtend.tests");
      suite.addTestSuite(org.eclipse.xtend.check.CheckAnalyzationTest.class);
      suite.addTestSuite(org.eclipse.xtend.check.CheckEvaluationTest.class);
      suite.addTestSuite(org.eclipse.xtend.check.CheckFastAnalyzerTest.class);
      suite.addTestSuite(org.eclipse.xtend.check.FeaturedCheckTest.class);
      suite.addTestSuite(org.eclipse.xtend.codeassist.FastAnalyzerTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.ast.AnalyzationTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.ast.EvaluationTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.codeassist.ExpressionProposalComputerTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.codeassist.ExtensionImportProposalComputerTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.codeassist.ReverseScannerTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.codeassist.TypeProposalComputerTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.EvaluationExceptionTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.ExecutionContextImplTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.parser.ParserTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.parser.ScannerTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.PolymorphismTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.ResourceManagerDefaultImplTest.class);
      suite.addTestSuite(org.eclipse.xtend.expression.TypeNameUtilTest.class);
      suite.addTestSuite(org.eclipse.xtend.ExtensionAnalyzationTest.class);
      suite.addTestSuite(org.eclipse.xtend.ExtensionEvaluationTest.class);
      suite.addTestSuite(org.eclipse.xtend.JavaExtensionTypeConversionTest.class);
      suite.addTestSuite(org.eclipse.xtend.parser.ExtensionParserTest.class);
      suite.addTestSuite(org.eclipse.xtend.PerformanceTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.CollectionFeaturesTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.ObjectFeaturesTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.types.BooleanTypeTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.types.CollectionTypeTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.types.EnumTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.types.IntegerTypeTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.types.ObjectTypeTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.types.RealAndIntegerTeamplayTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.types.RealTypeTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.types.StringTypeTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.types.TypeTypeTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.baseimpl.TypesComparatorTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.emf.check.cache.CachedExtensionTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.impl.javabeans.JavaBeansStrategyTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.javabeansimpl.test.JavaCustomCollectionsTest.class);
      suite.addTestSuite(org.eclipse.xtend.typesystem.javabeansimpl.test.JavaTest.class);
      suite.addTestSuite(org.eclipse.xtend.XtendComponentTest.class);
      suite.addTestSuite(org.eclipse.xtend.XtendFacadeTest.class);
      return suite;
   }
}
