/**
 * <copyright>
 * </copyright>
 *
 * $Id: ExtensionNodeValidator.java,v 1.1 2008/03/17 14:39:09 jkohnlein Exp $
 */
package org.eclipse.xpand3.internal.frontend.parser.xpand3node.validation;

import org.eclipse.tmf.common.node.CompositeNode;
import org.eclipse.tmf.common.node.LeafNode;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.internal.frontend.parser.xpand3node.ExtensionNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExtensionNodeValidator {
	boolean validate();

	boolean validateExtendBody(CompositeNode value);
	boolean validateReturnType(CompositeNode value);
	boolean validateCreatedName(CompositeNode value);
	boolean validatePrivate(LeafNode value);
	boolean validateJavaCall(CompositeNode value);
	boolean validateName(CompositeNode value);
	boolean validateCreate(LeafNode value);
	boolean validateCached(LeafNode value);
	boolean validateParamList(CompositeNode value);
}
