/**
 * <copyright>
 * </copyright>
 *
 * $Id: ForeachStatementNodeValidator.java,v 1.1 2008/03/17 14:39:10 jkohnlein Exp $
 */
package org.eclipse.xpand3.internal.frontend.parser.xpand3node.validation;

import org.eclipse.tmf.common.node.CompositeNode;

/**
 * A sample validator interface for {@link org.eclipse.xpand3.internal.frontend.parser.xpand3node.ForeachStatementNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ForeachStatementNodeValidator {
	boolean validate();

	boolean validateIterator(CompositeNode value);
	boolean validateIdentifier(CompositeNode value);
	boolean validateSequence(CompositeNode value);
	boolean validateForExpression(CompositeNode value);
	boolean validateSeparatorExpression(CompositeNode value);
}
