/**
 * <copyright>
 * </copyright>
 *
 * $Id: Test_expressionNodeValidator.java,v 1.1 2008/03/17 14:39:09 jkohnlein Exp $
 */
package org.eclipse.xpand3.internal.frontend.parser.xpand3node.validation;


/**
 * A sample validator interface for {@link org.eclipse.xpand3.internal.frontend.parser.xpand3node.Test_expressionNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Test_expressionNodeValidator {
	boolean validate();

}
